/////////////////////////////////////////////////////// WEEK 1

//LOCALHOST
### Local app
GET http://localhost:8000

//PRODUCTION
###  App through render
GET https://contacts-api.onrender.com

/////////////////////////////////////////////////////// WEEK 2

//*****************LOCAL***************** 

  //LIST CONTACTS
###  Local app
GET http://localhost:8000/contacts

  //CONTACTS 1 CONTACT BY ID
###  Local app
GET http://localhost:8000/contacts/6328a3caad12097a5eac8ee3

//*****************PRODUCTION***************** 

  //CONTACTS 1 CONTACT BY ID
###  App through render
GET https://contacts-api.onrender.com/contacts

  //CONTACTS 1 CONTACT BY ID
###  App through render
GET https://contacts-api.onrender.com/contacts/6328a3a5ad12097a5eac8ee2

/////////////////////////////////////////////////////// WEEK 3

//*****************LOCAL***************** 
  //POST FOR CONTACTS
###  Local app
POST http://localhost:8000/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Contact",
  "email": "tc@gmail.com",
  "favoriteColor": "red",
  "birthday": "2099-12-31"
}

  //PUT FOR CONTACTS (UPDATE FAVORITE COLOR)
###  Local app
PUT http://localhost:8000/contacts/633c77a1869464d12dc1bc6e
Content-Type: application/json

{
    "favoriteColor": "yellow"
}

  //DELETE FOR CONTACTS
###  Local app
DELETE  http://localhost:8000/contacts/633c77a1869464d12dc1bc6e


//*****************PRODUCTION***************** 
  //POST FOR CONTACTS
###  App through render
POST https://contacts-api.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Contact",
  "email": "tc@gmail.com",
  "favoriteColor": "red",
  "birthday": "2099-12-31"
}

  //PUT FOR CONTACTS (UPDATE FAVORITE COLOR)
###  App through render
PUT   http://localhost:8000/contacts/633c6565b66c7b40a0018a1d
Content-Type: application/json

{
    "favoriteColor": "orange"
}

  //DELETE FOR CONTACTS
###  App through render
DELETE  https://contacts-api.onrender.com/contacts/633c6565b66c7b40a0018a1d

/////////////////////////////////////////////////////// WEEK 3

//*****************LOCAL***************** 
  //GET FOR API DOCS
###  Local app
GET http://localhost:8000/api-docs

//*****************PRODUCTION***************** 
  //GET FOR API DOCS
###  App through render
GET https://contacts-api.onrender.com/api-docs
