/////////////////////////////////////////////////////// WEEK 1

//LOCALHOST
### Local app
GET http://localhost:8000

//PRODUCTION
###  Test app through render
GET https://real-name.onrender.com

/////////////////////////////////////////////////////// WEEK 2

//*****************LOCAL***************** 

  //LIST CONTACTS
###  Test app through render
GET http://localhost:8000/contacts

  //CONTACTS 1 CONTACT BY ID
###  Test app through render
GET http://localhost:8000/contacts/6328a2abad12097a5eac8ee0

//*****************PRODUCTION***************** 

  //CONTACTS 1 CONTACT BY ID
###  Test app through render
GET https://real-name.onrender.com/contacts

  //CONTACTS 1 CONTACT BY ID
###  Test app through render
GET https://real-name.onrender.com/contacts/6328a3a5ad12097a5eac8ee2

/////////////////////////////////////////////////////// WEEK 3

//*****************LOCAL***************** 
  //POST FOR CONTACTS
###  Test app through render
POST https://localhost:8000.com/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Contact",
  "email": "tc@gmail.com",
  "favoriteColor": "red",
  "birthday": "2099-12-31"
}

  //PUT FOR CONTACTS (UPDATE FAVORITE COLOR)
###  Test app through render
PUT https://localhost:8000.com/contacts
Content-Type: application/json

{
    "id": "6333a8e5768f671b85dba17d",
    "favoriteColor": "blue"
}

  //DELETE FOR CONTACTS
###  Test app through render
DELETE  https://localhost:8000.com/contacts
Content-Type: application/json

{
    "id": "63339d80db395883cc0edab3"}

//*****************PRODUCTION***************** 
  //POST FOR CONTACTS
###  Test app through render
POST https://real-name.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Contact",
  "email": "tc@gmail.com",
  "favoriteColor": "red",
  "birthday": "2099-12-31"
}

  //PUT FOR CONTACTS (UPDATE FAVORITE COLOR)
###  Test app through render
PUT https://real-name.onrender.com/contacts
Content-Type: application/json

{
    "id": "6333a8e5768f671b85dba17d",
    "favoriteColor": "blue"
}

  //DELETE FOR CONTACTS
###  Test app through render
DELETE  https://real-name.onrender.com/contacts
Content-Type: application/json

{
    "id": "63339d80db395883cc0edab3"}